name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build wheel and zip for PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build dist
        run: |
          python -m pip install twine build
          python -m build

      - name: Test the built distributions
        run: |
          cd dist/
          python -m pip install tcmarkers-*.whl
          python -c "import tcmarkers; print(tcmarkers.__version__)"

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: wheelhouse
          path: dist

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TCMARKER_PASSWORD }}
        run: |
          twine upload -u ${TWINE_USERNAME} -p ${TWINE_PASSWORD} dist/tcmarkers*