name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build wheel and zip for PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build dist
        run: |
          python -m pip install twine build
          python -m build

      - uses: actions/upload-artifact@v1
        with:
          name: wheelhouse
          path: dist

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TCMARKER_PASSWORD }}
        run: |
          twine upload -u ${TWINE_USERNAME} -p ${TWINE_PASSWORD} dist/tcmarkers*